### ISSUE TITLE
Docker Build Fails: copy of bootptab 

### ISSUE THREAD

**Issue by jkatzmandu** [frankeverdij/docker-irixinstall#1]
Running Ubuntu 22.04 and an install of docker that seems to work. Running "docker build" it fails on:

$ sudo docker build -t irix-install .
[......]
Step 10/19 : COPY bootptab /etc/bootptab
COPY failed: file not found in build context or excluded by .dockerignore: stat bootptab: file does not exist

bootpd is installed on the host OS, so I'm not sure what's going on here. Any pointers? Thanks!

**Comment by jkatzmandu** [comment]
I'm a moron. Didn't have the entire repo cloned.

**Comment by frankeverdij** [comment]
No worries, glad you're using it!
